name: Build and Deploy to NPM

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install 🔧
        run: |
          npm ci
          npm i @icemourne/tool-box @icemourne/description-converter

      - name: Build
        run: |
          npm run build

      - name: Version up
        run: |
          git config --global user.email "cboweris@gmail.com"
          git config --global user.name "Ice-mourne"
          git add .
          git commit
          npm version patch
          git commit

      # - name: Publish 📦
      #   uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.NPM_TOKEN }}
      #     tag: latest
      #     access: public
      #     dry-run: false

      # - name: commit to github repository
      #   run: |
      #     git config user.name Icemourne
      #     git config user.email cboweris@gmail.com
      #     git add .
      #     git commit -m "update version"
      #     git push
