name: Build and Deploy to NPM

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install and Build 🔧
        run: |
          npm ci
          npm version patch
          npm i @icemourne/tool-box @icemourne/description-converter
          npm run build

      - name: Publish 📦
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          tag: latest
          access: public
          dry-run: false

      - name: commit to github repository
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update version"
          git push
          
